DROP DATABASE IF EXISTS xo_final;

CREATE DATABASE IF NOT EXISTS xo_final;

USE xo_final;


CREATE TABLE xo_final.users
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  email VARCHAR(30) NOT NULL UNIQUE,
  login VARCHAR(30) NOT NULL UNIQUE,
  pass VARCHAR(30) NOT NULL,
  firstName VARCHAR(30) NOT NULL,
  lastName VARCHAR(30) NOT NULL,
);





